# Generated by Django 4.2.16 on 2024-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='categories',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Crypto', 'Crypto'), ('Helth', 'Health')], default='Tech', max_length=10),
        ),
    ]
