# Generated by Django 4.2.16 on 2024-10-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_userpreferences_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='categories',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='crypto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='tech',
            field=models.BooleanField(default=False),
        ),
    ]
